### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by eskp** [danielefavi/ethereum-vuejs-dapp#1]
Followed the instruction to setup the dev environment but unable to load the table.
Seeing "Connecting..." on the page. When opening Chrome dev console seeing errors from BcExplorer:
```
BcExplorer error: missing networkId in the compiled Truffle JSON.
BcExplorer error: contract is not initialized.
Uncaught (in promise) TypeError: Cannot read property 'isRegistered' of undefined
```

**Comment by danielefavi** [comment]
One of the reasons that error may occur is when the **network ID** in the file **~/ethereum-vuejs-dapp/app-users/src/assets/UsersContract.json** does not match with the network ID of the running blockchain.

To check it out open the file **UsersContract.json**, then scroll down to the bottom; you should see something like the following code:

    "networks": {
        "5777": {
            "events": {},
            "links": {},
            "address": "0x782b9ce19fe792ed3c4ccbfb439ab59ddc5369f2",
            "transactionHash": "0x90777f2694621fc1b1f908177ea3f90845973efddebb031348c7fb2aaa7200fa"
        }
    },
the ID you see (in this example is 5777) must be the same of the ID you see in Ganache.

In order to solve this problem try to do the following steps:
- start Ganache
- make sure that ganache is running on the Network ID 5777
- compile again the smart contract:
go to **~/ethereum-vuejs-dapp** then run the two commands:
`truffle console --network ganache`
`migrate --reset --compile-all`
- copy the content of the file **~/ethereum-vuejs-dapp/build/contracts/Users.json** into **~/ethereum-vuejs-dapp/app-users/src/assets/UsersContract.json**
- go under the folder **~/ethereum-vuejs-dapp/app-users** and run the command:
`npm run dev`
and wait for the message
- open the browser and refresh the page with CTRL+F5 (if you are using chrome) or CTRL+R (if you are using firefox)

**Comment by eskp** [comment]
So I'm starting from scratch.
Started ganache with
`ganache-cli -i 5777 -p 7545`
Run
`truffle --network ganache migrate --reset --all`
Copy the artefact to the app directory (btw this can probably be done better with truffle-contract module - I'm looking how to do this right now)
`cp build/contracts/Users.json app-users/src/assets/UsersContract.json`
Double check `cat app-users/src/assets/UsersContract.json`
```
...
"networks": {
    "5777": {
...
```
From `app-users` directory run
`npm install && npm run dev`
And unfortunately seeing the same errors. Missing something.

**Comment by danielefavi** [comment]
I just tried again from scratch with **ganache-cli** following your steps and everything worked fine.

Maybe in your browser there could be old files cached from previous tests, so you can try with cache-refresh or opening the browser in private mode.
That error appears when the settings in the _app-users/src/assets/UsersContract.json_ do not match the settings of the running blockchian.

From what you are saying I don't know how to get that error. If you have more details or you find out the solution please tell me.

**Comment by eskp** [comment]
It does seem to be a caching issue no matter what way I clear the cache. Private mode does show the application. I'll continue looking. Thanks @danielefavi

**Comment by phutchins** [comment]
I'm seeing the same behavior as well. Anyone have thoughts on this? In the dev tools when browsing in normal mode I get...

BcExplorer error: missing networkId in the compiled Truffle JSON

and

BcExplorer error: contract is not initialized

But when running in incogneto mode, everything appears fine.

**Comment by phutchins** [comment]
Looks like when bcExpolorer is running getNetworkId() in normal browsing it gets set to 1 while in incognito mode its set to the correct value 5777 in my case. Still not quite sure why.

**Comment by danielefavi** [comment]
@phutchins Usually when you get 1 from `getNetworkId()` means you are connected to the Ethereum MAINNET. Ganache chain ID usually 1337.  
Do you mind checking if you are connected to the right network on Metamask, please?
