### ISSUE TITLE
Profile Error - Cannot save

### ISSUE THREAD

**Issue by mattdunndc** [danielefavi/ethereum-vuejs-dapp#4]
Working with Solidity 0.5 but when you try to save a Profile, you get an invalid address error.

I am using Ganache and have imported all the accounts into MetaMask.

Uncaught (in promise) Error: invalid address

![image](https://user-images.githubusercontent.com/7073238/55803727-e8e77800-5aa8-11e9-8333-f9f8c4f6c688.png)

**Comment by danielefavi** [comment]
The issue was caused by the **privacy mode** introduced in the **version 6 of Metamask**. Metamask 6 does not inject a web3 instance like before; instead, dapps must request access to user accounts, which will in turn ask the user to approve or deny access to the Ethereum blockchain.

More info at:
https://medium.com/metamask/https-medium-com-metamask-breaking-change-injecting-web3-7722797916a8

**The dapp has been updated for Metamask 6.** Thanks for reporting!

NOTE: you can encounter on the following error:
```
Error: [ethjs-rpc] rpc error with payload [...]
the tx doesn't have the correct nonce. account has nonce of: 0 tx has nonce of: 12
```
The causes can be:
- You did not imported any account.
- You have made previous test on that account and you have to reset it (select the account imported test account, go to *Settings* > *Advanced* > click the button *RESET ACCOUNT*).

**Comment by danielefavi** [comment]
The issue was caused by the **privacy mode** introduced in the **version 6 of Metamask**. Metamask 6 does not inject a web3 instance like before; instead, dapps must request access to user accounts, which will in turn ask the user to approve or deny access to the Ethereum blockchain.

More info at:
https://medium.com/metamask/https-medium-com-metamask-breaking-change-injecting-web3-7722797916a8

**The dapp has been updated for Metamask 6.** Thanks for reporting!

NOTE: using the dapp you can encounter on the following error:
```
Error: [ethjs-rpc] rpc error with payload [...]
the tx doesn't have the correct nonce. account has nonce of: 0 tx has nonce of: 12
```
The causes can be:
- You did not imported any account.
- You have made previous test on that account and you have to reset it (open Metamask in your browser, select the imported test account, go to *Settings* > *Advanced* > click the button *RESET ACCOUNT*).

**Comment by mattdunndc** [comment]
Awesome!  Thank you so much for your time.  Really appreciate it. @danielefavi
