### ISSUE TITLE
Balance is always showing 0 ETH

### ISSUE THREAD

**Issue by mattdunndc** [danielefavi/ethereum-vuejs-dapp#5]
Really enjoying this app.  There seems to be a small issue with the Balance on the Profile view.

I am running Ganache with 10 samples accounts.  Why is the Balance showing 0?  

![image](https://user-images.githubusercontent.com/7073238/55974535-d5c5db00-5c55-11e9-8b6d-680ff9a6d5e5.png)

**Comment by mattdunndc** [comment]
Fixed!

Replace this line in Profile.vue 
//this.balance = window.bc.weiToEther( info.balance );

With this block:
// Get balance by info.mainAccount and then covert to Ether
    window.bc.getBalance(info.mainAccount)
          .then(data => window.bc.weiToEther(data) )
          .then(data => {
              this.balance = data
          })

![image](https://user-images.githubusercontent.com/7073238/55994819-c6a85280-5c80-11e9-8b68-df8581f53734.png)

**Comment by danielefavi** [comment]
Thanks @mattdunndc for your help!

As you suggested the problem was in the following piece of code:
```
window.bc.loadInfo().then(info => {
    this.userAddressAccount = info.mainAccount;

    this.balance = window.bc.weiToEther( info.balance );
});
```
Since I'm calling `loadInfo` I'm expecting `info.balance` to be filled up (and not always a null as before). So I moved what you suggested `window.bc.getBalance(info.mainAccount)` in the function `loadInfo` of the class `BcExplorer` rather than to update the line in *Profile.vue*.

Here you can see the changes made on the function `BcExplorer@loadInfo`:
https://github.com/danielefavi/ethereum-vuejs-dapp/blob/master/app-users/src/libs/BcExplorer.js#L379
I added `this.getBalance(account).then(balance => {` in the nested sequence of calls.
